"""empty message

Revision ID: 366728672b14
Revises: 6012286f51fd
Create Date: 2023-06-02 09:44:22.228187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366728672b14'
down_revision = '6012286f51fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
