"""empty message

Revision ID: 480b1df822e7
Revises: 52a7d14a4fff
Create Date: 2023-06-02 15:09:27.629474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480b1df822e7'
down_revision = '52a7d14a4fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritesPeople', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritesPeople', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
