"""empty message

Revision ID: db7b845a3c47
Revises: 366728672b14
Create Date: 2023-06-02 14:06:10.887144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7b845a3c47'
down_revision = '366728672b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritesPeople', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritesPeople', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
